### ISSUE TITLE
switch between "outside of view frame" and "occluded or obscured"

### ISSUE THREAD

**Issue by fdesmedt** [jldowns/vatic-docker-contrib#1]
Hi,
I have a problem in the following process: 
- I start labeling a pedestrian entering the frame and I annotate it as "occluded"
- I scroll further using the scrollbar and uncheck the "occluded" checkbox when the pedestrian is fully visible
- but when I scroll back to the earlier frames, the checkbox of "occluded" has changed to "outside of the view frame". Unchecking this seems to mess up the positions I defined before

Any idea what could be causing this?

**Comment by jldowns** [comment]
No, I'm not sure. I know I had a lot of problems annotating *exactly* when an object was outside the field of view. Messing around with the bounding boxes close to the frames where I selected the "outisde FOV" checkbox usually applied the "outside FOV" to the 3 or 4 previous frames as well. I thought it was because VATIC was recording each of the user's inputs as a "key frame," and if you didn't edit the bounding box before selecting a checkbox, the checkbox would be applied to every frame until the previous keyframe, but I don't think that's it. I think it might be a bug with how VATIC is applying the "outside FOV" checkbox to the frames.

It was super frustrating. I basically would apply the "outside FOV" checkbox to a few frames *after* a pedestrian left the frame in order for that checkbox to be applied to the previous few frames.

And unfortunately the bottom line is that I haven't gone into the VATIC source code to figure out exactly what's going on. Also, this isn't the VATIC repo; this just packaged VATIC into a Docker container.
